<?php

namespace Reviewer\ReviewBundle\Repository;

/**
 * genreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class genreRepository extends \Doctrine\ORM\EntityRepository
{

    public function getGenres()
    {
        $queryBuilder = $this->createQueryBuilder('genre');
        $queryBuilder->select('genre.genreName');
        $query = $queryBuilder->getQuery();
        var_dump($query->getResult);
        return $query->getResult();
    }

}
