<?php

namespace Reviewer\ReviewBundle\Repository;

/**
 * reviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reviewRepository extends \Doctrine\ORM\EntityRepository
{
}
