api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix: /api/v1

reviewer_review:
    resource: "@ReviewerReviewBundle/Resources/config/routing.yml"
    prefix:

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

reviewer_review_homepage:
    path:  /
    defaults: { _controller: ReviewerReviewBundle:Default:index }

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"



api_client:
  path: /account/api-client
  defaults: { _controller: ReviewerReviewBundle:Default:apiClient }