reviewer_review_homepage:
  path:  /
  defaults: { _controller: ReviewerReviewBundle:Default:index }

review_view:
  path:     /view/review/{id}
  defaults: { _controller: ReviewerReviewBundle:Review:viewReview }
  requirements:
    id: \d+

review_create:
  path:     /create/review/{isbn}
  defaults: { _controller: ReviewerReviewBundle:Review:createReview}

book_view:
  path:     /view/book/{id}
  defaults: {  _controller: ReviewerReviewBundle:Book:viewBook}
  requirements:
    id: \d+

book_create:
  path:     /create/book
  defaults: {  _controller:  ReviewerReviewBundle:Book:createBook}

book_genre:
  path:     /book/genre/{genreId}
  defaults: {  _controller: ReviewerReviewBundle:Book:viewBooksByGenre}
  requirements:
    genreId: \d+

search:
  path:  /search/{seachQuery}
  defaults: {  _controller: ReviewerReviewBundle:Filtering:submitSearch}

edit_review:
  path:     /edit/{id}/{isbn}
  defaults: { _controller: ReviewerReviewBundle:Review:editReview }
  requirements:
    id: \d+

delete_review:
    path:     /delete/{id}
    defaults: { _controller: ReviewerReviewBundle:Review:deleteReview }
    requirements:
        id: \d+

report_review:
  path:     /report/{id}
  defaults: {  _controller: ReviewerReviewBundle:Review:report}
  requirements:
    id: \d+