reviewer_review_homepage:
    path:  /
    defaults: { _controller: ReviewerReviewBundle:Default:index }

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

view:
    path:     /view
    defaults: { _controller: ReviewerReviewBundle:BookReview:view }

create:
    path:     /create
    defaults: { _controller: ReviewerReviewBundle:BookReview:create }

edit:
    path:     /edit
    defaults: { _controller: ReviewerReviewBundle:BookReview:edit }

delete:
    path:     /delete
    defaults: { _controller: ReviewerReviewBundle:BookReview:delete }
