#services:
#    reviewer_review.example:
#        class: Reviewer\ReviewBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
services:
  book_service:
    class: Reviewer\ReviewBundle\Service\BookService
    arguments: [ "@doctrine.orm.entity_manager" ]
