services:
  filtering_service:
    class: Reviewer\ReviewBundle\Service\FilteringService
    arguments: [ "@doctrine.orm.entity_manager" ]

  book_service:
    class: Reviewer\ReviewBundle\Service\BookService
    arguments: [ "@doctrine.orm.entity_manager" ]